### ISSUE TITLE
Naive implementation

### ISSUE THREAD

**Issue by ravivos** [mdoron/c-236370#4]
We want to implement a working paralell version where each block is a producer and a consumer to its and form its neighbours where the queue contains the modified blocks and generation

**Comment by mdoron** [comment]
Each block has a Producer and a Consumer who are responsible for it. 
In each generation of the block, the producer fills its queue with 8 new records, and the consumer takes the information it needs from the relevant producers.

**Comment by ravivos** [comment]
we need to debug now
